# Generated by Django 4.0.4 on 2022-08-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumbing', '0023_account_cashfromreceipts_alter_customer_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiptNumber', models.CharField(max_length=150)),
                ('customerName', models.CharField(blank=True, max_length=150)),
                ('modeOfPayment', models.CharField(default='Cash', max_length=100)),
                ('purchasedFrom', models.CharField(blank=True, default=0, max_length=150)),
                ('item_purchased', models.CharField(max_length=250)),
                ('quantity', models.CharField(blank=True, default=0, max_length=150)),
                ('price', models.CharField(blank=True, default=0, max_length=150)),
                ('totalAmountPaid', models.CharField(blank=True, default=0, max_length=150)),
                ('date', models.DateField(default='2022-08-13')),
            ],
        ),
        migrations.AlterField(
            model_name='cashinvoice',
            name='date',
            field=models.DateField(default='2022-08-13'),
        ),
        migrations.AlterField(
            model_name='cheques',
            name='date',
            field=models.DateField(default='2022-08-13'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date',
            field=models.DateField(default='2022-08-13'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='due_date',
            field=models.DateField(blank=True, default='2022-08-13', null=True),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='date',
            field=models.DateField(default='2022-08-13'),
        ),
        migrations.AlterField(
            model_name='payable',
            name='date',
            field=models.DateField(default='2022-08-13'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='date',
            field=models.DateField(default='2022-08-13'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='date',
            field=models.DateField(default='2022-08-13'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='date',
            field=models.DateField(default='2022-08-13'),
        ),
    ]
