# Generated by Django 4.0.4 on 2022-08-13 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plumbing', '0025_alter_quotationreceipt_modeofpayment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationreceipt',
            name='item_purchased',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plumbing.stock'),
        ),
    ]
