# Generated by Django 4.0.4 on 2022-08-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumbing', '0027_creditreceipt_quotationreceipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditreceipt',
            name='discount',
            field=models.CharField(blank=True, default=0, max_length=150),
        ),
        migrations.AddField(
            model_name='quotationreceipt',
            name='balance',
            field=models.CharField(blank=True, default=0, max_length=150),
        ),
        migrations.AddField(
            model_name='quotationreceipt',
            name='discount',
            field=models.CharField(blank=True, default=0, max_length=150),
        ),
    ]
