# Generated by Django 4.0.4 on 2022-08-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumbing', '0028_creditreceipt_discount_quotationreceipt_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerreceipt',
            old_name='balance',
            new_name='discountIndividualItem',
        ),
        migrations.AlterField(
            model_name='cashinvoice',
            name='date',
            field=models.DateField(default='2022-08-26'),
        ),
        migrations.AlterField(
            model_name='cheques',
            name='date',
            field=models.DateField(default='2022-08-26'),
        ),
        migrations.AlterField(
            model_name='creditreceipt',
            name='date',
            field=models.DateField(default='2022-08-26'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date',
            field=models.DateField(default='2022-08-26'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='due_date',
            field=models.DateField(blank=True, default='2022-08-26', null=True),
        ),
        migrations.AlterField(
            model_name='customerreceipt',
            name='date',
            field=models.DateField(default='2022-08-26'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='date',
            field=models.DateField(default='2022-08-26'),
        ),
        migrations.AlterField(
            model_name='payable',
            name='date',
            field=models.DateField(default='2022-08-26'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='date',
            field=models.DateField(default='2022-08-26'),
        ),
        migrations.AlterField(
            model_name='quotationreceipt',
            name='date',
            field=models.DateField(default='2022-08-26'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='date',
            field=models.DateField(default='2022-08-26'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='date',
            field=models.DateField(default='2022-08-26'),
        ),
    ]
