# Generated by Django 3.2.12 on 2022-09-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumbing', '0029_rename_balance_customerreceipt_discountindividualitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cartNo', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('receiptNumber', models.CharField(max_length=150)),
                ('item_purchased', models.CharField(max_length=250)),
                ('quantity', models.CharField(blank=True, default=0, max_length=150)),
                ('price', models.CharField(blank=True, default=0, max_length=150)),
                ('amount', models.CharField(blank=True, default=0, max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='cashinvoice',
            name='date',
            field=models.DateField(default='2022-09-07'),
        ),
        migrations.AlterField(
            model_name='cheques',
            name='date',
            field=models.DateField(default='2022-09-07'),
        ),
        migrations.AlterField(
            model_name='creditreceipt',
            name='date',
            field=models.DateField(default='2022-09-07'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date',
            field=models.DateField(default='2022-09-07'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='due_date',
            field=models.DateField(blank=True, default='2022-09-07', null=True),
        ),
        migrations.AlterField(
            model_name='customerreceipt',
            name='date',
            field=models.DateField(default='2022-09-07'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='date',
            field=models.DateField(default='2022-09-07'),
        ),
        migrations.AlterField(
            model_name='payable',
            name='date',
            field=models.DateField(default='2022-09-07'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='date',
            field=models.DateField(default='2022-09-07'),
        ),
        migrations.AlterField(
            model_name='quotationreceipt',
            name='date',
            field=models.DateField(default='2022-09-07'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='date',
            field=models.DateField(default='2022-09-07'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='date',
            field=models.DateField(default='2022-09-07'),
        ),
    ]
