# Generated by Django 3.2.12 on 2022-09-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumbing', '0030_auto_20220907_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(blank=True, default=0, max_length=150),
        ),
    ]
