# Generated by Django 3.2.12 on 2022-09-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumbing', '0032_auto_20220908_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='type',
            field=models.CharField(default='Cash', max_length=100),
        ),
    ]
