# Generated by Django 3.2.12 on 2022-09-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumbing', '0034_auto_20220912_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditreceipt',
            name='currency',
            field=models.CharField(default='SSP', max_length=250),
        ),
        migrations.AddField(
            model_name='customerreceipt',
            name='currency',
            field=models.CharField(default='SSP', max_length=250),
        ),
        migrations.AddField(
            model_name='quotationreceipt',
            name='currency',
            field=models.CharField(default='SSP', max_length=250),
        ),
    ]
