# Generated by Django 3.2.12 on 2022-09-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plumbing', '0035_auto_20220912_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditreceipt',
            name='payType',
            field=models.CharField(default='Cash', max_length=100),
        ),
        migrations.AddField(
            model_name='customerreceipt',
            name='payType',
            field=models.CharField(default='Cash', max_length=100),
        ),
        migrations.AddField(
            model_name='quotationreceipt',
            name='payType',
            field=models.CharField(default='Cash', max_length=100),
        ),
    ]
